services:
#  portal:
#    build: .
#    container_name: mp-dana
#    ports:
#      - 3001:80

#  backend:
#    build: ./backend
#    container_name: dana-backend
#    ports:
#      - 3000:80
  minio:
    image: quay.io/minio/minio
    container_name: minio-elie
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    user: "${UID}:${GID}"
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"

  mongodb:
    image: mongo:6-jammy
    container_name: mongodb-elie
    ports:
      - '27019:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  minio:
  dbdata6: